name:                trial-bot-concurrent
version:             0.1.0.0
github:              "unam3/trial-bot-concurrent"
license:             BSD3
author:              "Oleg Obnoskin"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trial-bot-concurrent#readme>

dependencies:
- base == 4.13.0.0
- trial-bot-vk
- trial-bot

ghc-options:
- -Wall
- -threaded

library:
  source-dirs: src

executables:
  trial-bot-concurrent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trial-bot-concurrent

tests:
  trial-bot-concurrent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trial-bot-concurrent
